### ISSUE TITLE
Unable to open the blank .rtf file created by this app 

### ISSUE THREAD

**Issue by arthurzqhu** [liufsd/NewFileHereMenu#1]
I'm not sure the technical details, but It looks like a blank .rtf file should at least take some disk space (like 194 bytes created by TextEdit.app), instead 0 byte as shown in the screen shot. I think that's what caused this bug.

<img width="512" alt="screen shot 2016-11-17 at 00 39 15" src="https://cloud.githubusercontent.com/assets/3490251/20381889/5213da40-ac5e-11e6-89ed-c260f223bb13.png">

<img width="532" alt="screen shot 2016-11-17 at 00 33 39" src="https://cloud.githubusercontent.com/assets/3490251/20381820/02eb61ea-ac5e-11e6-9195-6c4b15c63c1a.png">

**Comment by liufsd** [comment]
HI~ which version do you use? Do you have update to new version  1.1.1 ?

**Comment by arthurzqhu** [comment]
Yeah, that solves the problem. Thank you!

Best,

Arthur

On Fri, Nov 25, 2016 at 06:25 liupeng

<
mailto:liupeng <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

HI~ which version do you use? Do you have update to new version 1.1.1 ?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/liufsd/NewFileHereMenu/issues/1#issuecomment-262966602
, or
