### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by rk492** [liufsd/NewFileHereMenu#11]
Hi! I have some ideas to improve Easy New File like adding a Cut option, a refresh items option or show/hide hidden items.

**Comment by rk492** [comment]
2. Add an option to create pages, keynote and numbers document. 
3. Select the kind of documents we want

**Comment by liufsd** [comment]
hi.
1.cut file & show/hide not be allowed on appstore app.
2. keynote, you can create it now . pages & numbers , i will be later.
3.yes. i will do it next version.

https://github.com/liufsd/NewFileHereMenu/issues/2

Thanks.

**Comment by liufsd** [comment]
v3.0 support custom file template by yourself.
