### ISSUE TITLE
希望新建文件子菜单里可以完全自定义

### ISSUE THREAD

**Issue by wadjj** [liufsd/NewFileHereMenu#2]
包括内建的选择on/off，以及自建自己需要的（可以通过指定某个自定义文件的方式）。
自建的方式大概类似于，我想添加.ai，就选中一个自己已经建好的空白ai文件。
这样不光能新建纯粹空白文件，还可以快速生成模板类文件，提高工作效率。

**Comment by liufsd** [comment]
好的 感谢您的反馈~ 我加入到TO DO LIST中去

**Comment by leon618** [comment]
我也希望可以选择模版

**Comment by liufsd** [comment]
好的 等忙完这段时间了 我在抽空做吧 
谢谢反馈

**Comment by JackTonyMa** [comment]
同样的需求＋1

**Comment by liufsd** [comment]
好的，下周末抽空实现下，最近忙于工作。sorry。
下周末一定抽空是线下。
感谢大家支持。

**Comment by chatree2527** [comment]
Download new file

**Comment by liufsd** [comment]
@chatree2527 
Sunday 17 Sep will publish next new version.

**Comment by JackTonyMa** [comment]
请问是18号更新的那版吗，没看到区别呀🤣 @liufsd @

**Comment by liufsd** [comment]
sorry @zhouchang714  还没来得急做。 非常抱歉。后面一定补上。最近比较忙。

**Comment by liufsd** [comment]
3.0 已支持
请大家更新到最新3.0版本即可。
感谢大家一直以来的支持。
中秋节快乐
![image](https://user-images.githubusercontent.com/1910405/31160708-055a38c0-a898-11e7-852e-cd1a9a955857.png)
![image](https://user-images.githubusercontent.com/1910405/31160715-152a8f02-a898-11e7-884a-1f7544988de9.png)
