### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by michaelxxw** [liufsd/NewFileHereMenu#3]
NewFileHereMenu非常方便，第一时间购买下载了，然后萌发了自己来试试去实现的想法，经过研究，碰到了使用Finder Sync Extension 创建文件，因未被授权而失败的问题，请问作者是怎么解决权限问题的？我看了Authorization Services Tasks的相关文档，以及示例代码：EvenBetterAuthorizationSample，只是运行起来也是报错，比如“error CFErrorDomainLaunchd / 2”，所以还是一头雾水。我是Mac开发初学者，望不吝赐教，谢谢哈

**Comment by liufsd** [comment]
未被授权而失败的问题?

**Comment by michaelxxw** [comment]
比如，我在Finder Sync Extension中，使用NSFileManager的createDirectoryAtPath方法，尝试创建一个文件夹，路径是：“/Users/xuxinwu/Desktop/aaa”，会报Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “aaa” in the folder “Desktop”."的错误，所以我以为是要先给它授权，但一直没尝试成功。我想，是不是我的思路不对？

**Comment by liufsd** [comment]
ok~ 
原因sandbox，默认是没有权限写文件的。

**Comment by michaelxxw** [comment]
是的，我也意识到了，所以就去研究授权服务，就是Authorization Services Tasks，但看了文档，下载了官方示例，虽然能跑起来，但都授权失败了。是要使用XPCService么？

**Comment by liufsd** [comment]
https://developer.apple.com/library/content/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW16

**Comment by michaelxxw** [comment]
好的，非常感谢，我先研究下，有问题再向你请教~~
