### ISSUE TITLE
希望优化一下用户逻辑

### ISSUE THREAD

**Issue by JackTonyMa** [liufsd/NewFileHereMenu#6]
这个工具非常棒，提一个建议，希望右键新建文件时候直接在当前路径创建，而不是需要再次确认。绝大多数情况下的需求也确实如此，文件名尾部自动加上序号以防止文件重复，现在右键新建文件还要跳出来文件名，存储路径的确认框实在是有些影响体验

**Comment by liufsd** [comment]
感谢反馈哦。
我抽空看下，是否可以修改下。
（之所以需要确认，其实是因为Mac系统本身为了安全考虑，不给第三方APP读写文件权限，需要用户确认后才可以写入。）

**Comment by JackTonyMa** [comment]
有一个aflred的workflow可以直接创建并打开新文件不需要确认， 地址贴在这里，我不是很懂，希望能够有帮助https://raw.githubusercontent.com/packal/repository/master/com.vitorgalvao.alfred.newfile/newfile.alfredworkflow

**Comment by liufsd** [comment]
您好，因为这些APP不是沙盒，换句话说是不受系统限制的。所以可以做任何事情。我的是走的store正常流程，所以限制比较多，苹果主要是为了你的安全。
