### ISSUE TITLE
Translation!

### ISSUE THREAD

**Issue by rk492** [liufsd/NewFileHereMenu#7]
Hi! I can help you to translate it to Spanish if you are interested in.

**Comment by liufsd** [comment]
wow. thanks.
please tell me your email,  i will send files to you.
my email: liupwade@gmail.com

**Comment by rk492** [comment]
Hi! I am not a developer but I can help you to translate the app. I will do
I can!

Rv.vera92@gmail.com



El 8 de septiembre de 2017 a las 12:06:36, liupeng (notifications@github.com)
escribió:

wow. thanks.
please tell me your email, i will send files to you.
my email: liupwade@gmail.com

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/liufsd/NewFileHereMenu/issues/7#issuecomment-328063272>,
or mute the thread

**Comment by liufsd** [comment]
hi . please check your email~
thanks.

**Comment by liufsd** [comment]
Hello.
You can download here: https://github.com/liufsd/NewFileHereMenu/tree/master/Localizable
And then send  your translate result to me . liupwade@gmail.com

**Comment by dee6600** [comment]
want a translation in hindi or marathi? i can do that

**Comment by liufsd** [comment]
@dee6600  wow. 👍.
Download this file:  https://github.com/liufsd/NewFileHereMenu/tree/master/Localizable
And then send your translate result to me . liupwade@gmail.com
I will send you my app by your translated.

**Comment by dee6600** [comment]
okay , i will try my best (y) :)

**Comment by dee6600** [comment]
hey i m new to this , should i change the key or the string ?

**Comment by liufsd** [comment]
no, you just translate the value.

**Comment by dee6600** [comment]
okay

**Comment by dee6600** [comment]
i have sent the mail just check it :)
