### ISSUE TITLE
2.1版本Finder工具栏下拉菜单中文显示不对

### ISSUE THREAD

**Issue by juvenrui** [liufsd/NewFileHereMenu#8]
如题所示，Finder工具栏下拉菜单显示的简体中文是不对的（FINDER_MENU_ITEM_NEW_TERMINAL_HEREE），多了一个字符E。但在Localizable.strings显示是正确的。

`<key>FINDER_MENU_ITEM_NEW_TERMINAL_HEREE</key>
	<string>打开终端</string>`

**Comment by liufsd** [comment]
好的。
感谢反馈。
后面改进。~ 。~

**Comment by liufsd** [comment]
2.2 fix
